server:
  port: 80
  servlet:
    context-path: /
    session:
      timeout: 120m
  compression:
    enabled: true
    mime-types: application/json,application/javascript,application/xml,application/font-woff2,application/font-woff,text/css,text/html,text/xml,text/plain
    min-response-size: 2048
    
spring:
  session:
    store-type: redis
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  thymeleaf:
    cache: true
    encoding: UTF-8
    mode: HTML5
    prefix: classpath:/templates/
    suffix: .html
  cloud:
    consul:
      enabled: true
      host: ${consul-host:127.0.0.1}
      port: ${consul-port:8500}
      discovery:
        register: true
        prefer-ip-address: true
        # hostname: ${spring.cloud.client.ip_address}
        health-check-path: ${management.server.servlet.context-path}/health
        health-check-interval: 10s
  redis:
    host: ${redis-host}
    port: ${redis-port}
    password: ${redis-password}
    jedis:
      pool:
        min-idle: 10
        max-idle: 50
        max-wait: -1
        max-active: 200
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: NON_NULL

management:
  endpoint:
    health:
      enabled: true
    metrics:
      enabled: true
  server:
    servlet:
      context-path: /actuator