server:
  port: 8200
  servlet:
    context-path: /
    
spring:
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  cloud:
    consul:
      enabled: true
      host: ${consul-host:127.0.0.1}
      port: ${consul-port:8500}
      discovery:
        register: true
        prefer-ip-address: true
        #hostname: ${spring.cloud.client.ip_address}
        health-check-path: ${management.server.servlet.context-path}/health
        health-check-interval: 10s
  redis:
    host: ${redis-host}
    port: ${redis-port}
    password: ${redis-password}
    jedis:
      pool:
        min-idle: 10
        max-idle: 50
        max-wait: -1
        max-active: 200
  datasource:
    url: jdbc:mysql://${mysql-host}:${mysql-port}/${mysql-database}?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false&allowMultiQueries=true&useSSL=false
    username: ${mysql-user}
    password: ${mysql-password}
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 50
    initialSize: 10
    maxWait: 60000
    minIdle: 10
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: NON_NULL
    
mybatis:
  type-aliases-package: com.biocloo.bic,com.gitee.myclouds
  mapper-locations: classpath*:**/*Mapper.xml
  config-location: classpath:mybatis-config.xml
  
management:
  endpoint:
    health:
      enabled: true
    metrics:
      enabled: true
  server:
    servlet:
      context-path: /actuator