# hystrix.command.fallbackcmd.execution.isolation.thread.timeoutInMilliseconds: 8000
server:
  port: 8080
  servlet:
    context-path: /
    
spring:
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  redis:
    host: ${redis-host}
    port: ${redis-port}
    password: ${redis-password}
    jedis:
      pool:
        min-idle: 10
        max-idle: 50
        max-wait: -1
        max-active: 200
  cloud:
    consul:
      enabled: true
      host: ${consul-host:127.0.0.1}
      port: ${consul-port:8500}
      discovery:
        register: true
        prefer-ip-address: true
        #hostname: ${spring.cloud.client.ip_address}
        health-check-path: ${management.server.servlet.context-path}/health
        health-check-interval: 10s
    gateway:
      routes:
      - id: myclouds-system
        uri: lb://myclouds-system-service  # 服务中心的实例名；lb(load balance)启用客户端负载均衡
        predicates:
        - Path=/admin/system/**
        filters:
        - name: Hystrix  # 熔断Filter
          args:
            name: booksFallbackCommand
            fallbackUri: forward:/fallback/books   # 降级处理
      
management:
  endpoint:
    health:
      enabled: true
    metrics:
      enabled: true
  server:
    servlet:
      context-path: /actuator